### ISSUE TITLE
Names for csv files

### ISSUE THREAD

**Issue by jbkunst** [datacampfire/FCI-Challenge#1]
Hi @pachamaltese ,

Remember it could be nice if the files have descriptive names instead of `PP0008.csv` pattern, so will be easy to the participants make an idea of what is the type of info in the table.

**Comment by pachadotdev** [comment]
hi @jbkunst 
sure !! I forgot that, but I made that with columns
right now I'm trying to "fix" a stupid error to compute some datasets for work
